pagemachine/ats

.travis.yml
Move to a separate build stage which defaults to PHP 7 and simplify removal for PHP 5.6
=> [TASK] Optimize codestyle build flow

.travis.yml
Simplify the whole configuration and drop extra PHP lint step since we run this on every test step anyways.
=> [TASK] Streamline build configuration

Classes/Controller/Backend/ApplicationController.php
__CLASS__ refers to the class the code is implemented in, while static::class uses the actual class of the current object (which inherits the code).
The latter is correct here as f.ex. the ArchivedApplicationController can have different ACL settings than the ApplicationController.
=> [BUGFIX] Wrong class used for menu urls when checking ACLs

Classes/Domain/Model/ApplicationB.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Backend/Application/Field/SelectCountry.html, Resources/Private/Partials/Backend/Application/Field/SelectNationality.html, Resources/Private/Partials/Backend/Application/Field/SelectTranslated.html, Resources/Private/Partials/Backend/Application/Field/Selectbox.html
These empty fields should prevent that the first option in a selectfield is automatically set once the edit form is saved - even if the field was initially blank (because no FE input was given).
=> [BUGFIX] Add empty default options for all BE application select fields

Classes/Controller/Backend/AbstractBackendController.php
This prevents FlashMessages like 'An error occured in ....Controller'. Since proper validation error messages are present, these technical errors have no use.
=> [TASK] Supress technical error messages in backend controllers

Classes/Controller/Backend/AbstractBackendController.php, Classes/Controller/Backend/ApplicationController.php, Classes/Controller/Backend/StatisticsController.php, Resources/Private/Language/locallang.xlf
This was the cause for non-translated menu headlines.
With this fix all controllers use the same docheader menu code.
(Moved the code to AbstractBackendController, controllers without header menus skip the function completely)
=> [BUGFIX] Statistics module uses different docheader menu code

Classes/Service/ExtconfService.php, Classes/Service/MailService.php, Tests/Unit/Service/MailServiceTest.php, ext_conf_template.txt
Some customers may not want to always use the system/ATS-wide email name and address when sending mails to applicants via backend.
This PR adds a config option to enable usage of backend user email addresses on a system-wide level (true by default to ensure backwards compatibility).
=> [FEATURE] Add config option to use BE user credentials in mails (true by default)

Classes/Controller/Backend/NotificationApplicationController.php, Classes/Domain/Model/ApplicationB.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Backend/Message/CommonFields.html, Resources/Private/Templates/Backend/NotificationApplication/NewMassNotification.html
... and crashing in the result. Sending mails is now only selectable in massage actions when a mail address is present.
=> Prevent mail actions from being available for applications without email

Classes/Controller/Application/AbstractApplicationController.php, Classes/Controller/Application/SubmitController.php, Classes/Controller/JobController.php, Classes/Service/TyposcriptService.php, Configuration/FlexForms/FlexformJobs.xml, Configuration/TypoScript/constants.txt, Configuration/TypoScript/setup.txt, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang_db.xlf, Tests/Unit/Controller/Application/AbstractApplicationControllerTest.php, Tests/Unit/Controller/JobControllerTest.php, Tests/Unit/Service/TyposcriptServiceTest.php
This PR adds the config option to set a custom "thank you"-page. The applicant will be redirected to this page after successful submit.
Also, Flexform setting overrides were only applied to job list and single view, not the application form. This is also fixed in the first commit.
Please test:
- If the constant "afterSubmitPage" contains a page ID, the form will redirect to it after submit.
- Overrides via plugin Flexform settings should also work.
Checks if a page exists are intentionally left out in the redirect part. It is the job of the integrator/editor to make sure a page exists. This is what the wizards inside the plugin FlexForm are for, editors can use them if constant format is unclear.
=> Custom thank you page

Classes/Command/AnonymizeCommandController.php, Classes/Command/ApplicationsCommandController.php, Classes/Domain/Model/AbstractApplication.php, Classes/Domain/Repository/AbstractApplicationRepository.php, Classes/Domain/Repository/AnonymizationTrait.php, Classes/Domain/Repository/ApplicationRepository.php, Classes/Service/AnonymizationService.php, Configuration/TCA/tx_ats_domain_model_application.php, Configuration/TypoScript/Backend/anonymization.ts, Configuration/TypoScript/Backend/setup.ts, Configuration/TypoScript/Backend/setup_legacy.ts, Documentation/Configuration/Index.rst, Tests/Unit/Domain/Repository/AbstractApplicationRepositoryTest.php, Tests/Unit/Domain/Repository/AnonymizationTraitTest.php, ext_localconf.php, ext_tables.sql
This PR adds a new command which anonymizes applications.
Anonymization format, minimum age and conditions  can be configured via TypoScript (see anonymization.ts and documentation for details).
The default configuration anonymizes applications  if they are **archived**, **unpooled** and **older than 90 days** (creation date). It also anonymizes all their appended children (notes, history...) and deletes associated files.
=> Anonymization via Scheduler (GDPR)

Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Application/Field/Language.html
- Translate language dropdown default ("select")
- Present one (empty) language form if languages are mandatory (so users do not have to click "add" for the mandatory language entry)
=> Improve language selects

Classes/Command/ApplicationsCommandController.php, Classes/Service/AnonymizationService.php, Configuration/TypoScript/Backend/anonymization.ts, Documentation/Security/Index.rst
This PR changes the anonymization config structure to hold multiple "presets" which can be selected in the command/scheduler task.
This allows for different conditions and field configs targeting the same object type.
Also, two default presets are now available:
- Archived: Anonymizes archived applications (not in pool) after 3 months
- Pooled: Anonymizes archived applications kept in the pool after 1 year
=> Multiple anonymization presets for archived and pooled applications

Configuration/TypoScript/Backend/setup_legacy.ts
This causes an error in BE if legacy TypoScript is active.
No need to merge options since the legacy option will be dropped in V2 anyway.
=> [BUGFIX] Missing rating options in legacy backend TypoScript

Classes/Application/ApplicationRating.php
This results in errors while property mapping, as the value '0' (default) should always be available
=> [BUGFIX] Default rating option is not properly registered

Classes/Message/AbstractMessage.php, Classes/Service/MailService.php, Tests/Unit/Message/AbstractMessageTest.php, Tests/Unit/Message/InviteMessageTest.php
This is accomplished quite easily by using TYPO3 core MailUtility functionality which parses comma-separated strings accordingly (also, its output is always an array, yay! No mixed types...).
=> [BUGFIX] Allow for multiple CC/BCC addresses in mail messages

Classes/Controller/Backend/ApplicationController.php, Classes/Controller/Backend/ArchivedApplicationController.php, Classes/Controller/Backend/NotificationApplicationController.php, Classes/Domain/Repository/JobRepository.php, Classes/Service/ExportService.php, Resources/Private/Language/de.locallang_db.xlf, Resources/Private/Language/locallang_db.xlf, Tests/Unit/Controller/Backend/ApplicationControllerTest.php
This allows for cleaner lists in BE - once a job application process is finished, the job is no longer available in filters and job selects.
New visibility mask for application modules:
- Applications (main), Mass Notification: Lists only **non-hidden** and **active** jobs
- Archive/Pools, Statistics: Lists  all jobs except deleted ones
=> [FEATURE] Use deactivated flag to show/hide job in applications module

Configuration/TCA/tx_ats_domain_model_job.php
This affects the user/usergroup fields which handle assignment in backend modules.
Since jobs can also have auto-assigned department groups (which are created on the fly), the requirement here does not always make sense.
Also, it should be possible to create jobs without any workflow implication - the simplest case.
=> Make user fields optional in job

composer.json
Old versions are kept as fallback for PHP 5.x.
=> [TASK] Update phpunit/phpunit to 6.x and nimut/testing-framework to 4.x

Resources/Private/Partials/Backend/Application/History/Message/fields.html
fields.html is a duplicate of Fields.html. This might lead to a conflict when using it in a case insensitive file system. UpperCamelCase is the recommendet naming for partial files, so fields.html is not needed at all.
=> [TASK] remove duplicate partial file fields.html

composer.json
This is deprecated and all packages should be available on Packagist
instead.
=> Drop TYPO3 Composer repository
