.travis.yml
=> [TASK] Reduce TER upload size

Classes/Domain/Model/ApplicationC.php
=> [BUGFIX] Fix broken FQCN

Classes/Controller/Backend/ApplicationController.php, Classes/Message/AbstractMessage.php, Classes/Service/FluidRenderingService.php, Resources/Private/Templates/Backend/Application/Acknowledge.html, Resources/Private/Templates/Backend/Application/Invite.html, Resources/Private/Templates/Backend/Application/Reject.html, Resources/Private/Templates/Backend/Application/Reply.html, Resources/Private/Templates/Backend/NotificationApplication/NewMassNotification.html, Tests/Unit/Controller/Backend/ApplicationControllerTest.php, Tests/Unit/Message/AbstractMessageTest.php, Tests/Unit/Message/InviteMessageTest.php
Allows inserting markers inside the subject field in messages.
=> Subject markers

Classes/Service/FluidRenderingService.php, Classes/Service/MailService.php, Classes/Service/PdfService.php, Resources/Private/Templates/Mail/Html.html, Resources/Private/Templates/Pdf/Body.html, Tests/Unit/Service/MailServiceTest.php, Tests/Unit/Service/PdfServiceTest.php
Adds separate content templates for mails and pdfs. This is very important for creating individual pdfs and mails in company layout.
=> Better messagetemplates

Configuration/TypoScript/Backend/constants.ts, Configuration/TypoScript/Backend/constants_legacy.ts, Configuration/TypoScript/Backend/setup.ts, Configuration/TypoScript/Backend/setup_legacy.ts, Configuration/TypoScript/setup.txt, Documentation/Index.md, Documentation/TypoScriptConfiguration.md, ext_conf_template.txt, ext_tables.php, ext_typoscript_constants.txt, ext_typoscript_setup.txt
Keep plugin and module settings separate and remove all plugin TypoScript from automatic inclusion.
Also, documentation for TS settings.
=> Typoscript cleanup

Classes/Controller/Application/QualificationsController.php, Classes/Domain/Model/ApplicationC.php, Classes/Domain/Model/LanguageSkill.php, Classes/Domain/Validator/LanguageSkillValidator.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Application/Field/Language.html
This PR changes the application form so at least one language skill is mandatory.
Skill fields are also validated with a custom validator to ensure a dropdown language or text language is given.
=> Mandatory languagefields

Classes/Domain/Model/ApplicationE.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Application/Field/Upload.html
This PR makes the file upload field mandatory (so at least one document must be uploaded).
It also improves error output.
=> Mandatory filefield

Classes/Controller/Application/SubmitController.php, Tests/Unit/Controller/Application/SubmitControllerTest.php
If the application is submitted over the FE form, set the application type to "Website".
=> Website Application Type

Classes/Domain/Model/Job.php, Configuration/TCA/Overrides/tx_ats_domain_model_job.php, Resources/Private/Partials/Job/Categories.html, Resources/Private/Templates/Job/Show.html
Adds category section to jobs  and default category list in job template.
=> Categorizable jobs

Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Backend/Application/Field/SubmitButton.html, Resources/Private/Partials/Backend/Application/Form/Rating.html, Resources/Private/Partials/Backend/Application/Form/StatusChange.html, Resources/Private/Partials/Backend/SharedApplicationActions/Clone.html, Resources/Private/Partials/Backend/SharedApplicationActions/Edit.html, Resources/Private/Partials/Backend/SharedApplicationActions/Notes.html, Resources/Private/Templates/Backend/Application/BackToPerso.html, Resources/Private/Templates/Backend/Application/New.html, Resources/Private/Templates/Backend/ArchivedApplication/MoveToPool.html, Resources/Private/Templates/Backend/ArchivedApplication/NewMassPoolMoving.html
Merge all submit labels into one and make the submit button primary (bootstrap).
=> Standardize BE submit buttons

Classes/Controller/Backend/ApplicationController.php, Classes/Domain/Model/Application.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Partials/Backend/Application/Form/General.html, Tests/Unit/Controller/Backend/ApplicationControllerTest.php
This allows for manually entered receiptdates (think of applications sent on paper which need to be added into the system)
=> [FEATURE] Add receiptdate field to BE application forms

Classes/Domain/Model/StructuredJobDefinitionTrait.php, Resources/Private/Partials/Job/JsonLd.html
=> [BUGFIX] JsonViewHelper error in TYPO3 7 when displaying structured data

Resources/Private/Partials/Application/Field/SelectNationality.html
This bug was introduced with PR https://github.com/pagemachine/ats/pull/95.
=> [BUGFIX] Default nationality is not saved as ISO3 code

Classes/Controller/Application/AbstractApplicationController.php, Classes/Controller/Application/QualificationsController.php, Resources/Private/Language/de.locallang.xlf, Resources/Private/Language/locallang.xlf, Resources/Private/Partials/Application/Field/Checkbox.html, Resources/Private/Partials/Application/Field/Label.html, Resources/Private/Partials/Application/Field/Language.html, Resources/Private/Partials/Application/Field/RadioButton.html, Resources/Private/Partials/Application/Field/SelectCountry.html, Resources/Private/Partials/Application/Field/SelectNationality.html, Resources/Private/Partials/Application/Field/SelectTranslated.html, Resources/Private/Partials/Application/Field/Selectbox.html, Resources/Private/Partials/Application/Field/TextField.html, Resources/Private/Partials/Application/Field/Textarea.html, Resources/Private/Partials/Application/Field/Upload.html, Tests/Unit/Controller/Application/AbstractApplicationControllerTest.php, Tests/Unit/Controller/Application/QualificationsControllerTest.php
based on validation rules.
For example, the label "First name:" will change to "First name*:" if validation rules for the corresponding property exist.
The asterisk is added as soon as the validation rules are not empty for this field.
=> [FEATURE] Automatically add asterisk to mandatory fields

Classes/Controller/Application/AbstractApplicationController.php, Classes/Controller/Application/AdditionalDataController.php, Classes/Controller/Application/FormController.php, Classes/Controller/Application/PersonalDataController.php, Classes/Controller/Application/QualificationsController.php, Classes/Controller/Application/SubmitController.php, Classes/Controller/Application/UploadController.php, Classes/Controller/Backend/ApplicationController.php, Classes/Controller/Backend/StatisticsController.php, Classes/Controller/JobController.php, Classes/Domain/Repository/AbstractApplicationRepository.php, Classes/Domain/Validator/TypoScriptValidator.php, Classes/Message/AbstractMessage.php, Classes/Message/MessageFactory.php, Classes/Property/TypeConverter/UploadedFileReferenceConverter.php, Classes/Service/AuthenticationService.php, Classes/Service/ExportService.php, Classes/ViewHelpers/Form/UploadViewHelper.php, Classes/ViewHelpers/Workflow/ApplicationActionsViewHelper.php
Build is allowed to fail as tests still use old DatabaseConnection code (this will be resolved in a different PR).
=> [TASK] Replace @inject-Annotations with inject methods

Classes/Message/MessageFactory.php, Documentation/Development/Index.rst, Documentation/Index.rst, Tests/Unit/Message/MessageFactoryTest.php
Add signal to manipulate mail messages before they are passed to mail forms.
=> Add mail message signal

Documentation/Configuration/Index.rst, Documentation/Security/Index.rst
- Describe which property is used for lifetime calculation (creationDate for applications, lastlogin for users)
- Document cleanup settings in configuration part
=> [DOCS] Improve anonymization/cleanup documentation

Classes/Domain/Model/History.php, Classes/Service/ExportService.php, Resources/Private/Partials/Backend/Application/History/rating.html, Resources/Private/Partials/Backend/Application/History/ratingPerso.html, Resources/Private/Partials/Backend/Application/Overview.html, Resources/Private/Partials/Backend/Application/TableInner.html
Also, fix some translations inside overviews for custom ratings.
=> Handle invalid ratings with missing translations

Resources/Private/Partials/Backend/Application/TableInner.html, Resources/Public/Css/backend.css
- Fix row count starting at 0
- Add icons for current ordering state and add cursor:pointer to hint at order functionality
=> Small application table fixes to improve look-and-feel

docker-compose.yml
We do not really need a constantly running process here.
=> Use CLI PHP image
